// resources/js/Pages/auth/forgot-password.svelte
<script lang="ts">
    import { inertia, router } from "@inertiajs/svelte";
    import NaraIcon from "../../Components/NaraIcon.svelte";
    import DarkModeToggle from "../../Components/DarkModeToggle.svelte";
    import axios from "axios";
    import { api } from "../../Components/helper";

    interface ForgotPasswordForm {
        email: string;
        phone: string;
    }

    let form: ForgotPasswordForm = {
        email: "",
        phone: "",
    };

    let success: boolean = false;
    export let error: string | undefined;

    async function submitForm(): Promise<void> {
        const result = await api(() => axios.post("/forgot-password", form));
        
        if (result.success) {
            success = true;
            form.email = "";
            form.phone = "";
        }
    }
</script>

<section class="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 text-slate-50">
    <!-- Header with dark mode toggle -->
    <header class="fixed inset-x-0 top-0 z-40 border-b border-slate-800/60 bg-slate-950/80 backdrop-blur-xl">
        <div class="max-w-6xl mx-auto flex h-16 items-center justify-between px-4 sm:h-20 sm:px-6 lg:px-8">
            <a href="/" use:inertia class="flex items-center gap-2">
                <img src="/public/nara.png" alt="Nara logo" class="h-7 w-7 rounded-lg object-cover" />
                <div class="flex flex-col leading-tight">
                    <span class="text-sm font-semibold tracking-tight text-slate-50">Nara</span>
                    <span class="text-[10px] uppercase tracking-[0.22em] text-slate-500">TypeScript framework</span>
                </div>
            </a>
            <div class="flex items-center gap-3">
                <DarkModeToggle />
            </div>
        </div>
    </header>

    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto min-h-screen lg:py-0">
        <div class="flex items-center mb-6 text-2xl font-semibold text-slate-50">
            <NaraIcon></NaraIcon>
        </div>
        <div class="w-full max-w-md rounded-3xl border border-slate-800/80 bg-slate-900/70 backdrop-blur-xl shadow-[0_24px_80px_rgba(15,23,42,0.8)] md:mt-0 sm:max-w-md xl:p-0">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl font-bold leading-tight tracking-tight text-slate-50 md:text-2xl">
                    Reset Password
                </h1>

                {#if error}
                    <div class="p-4 mb-4 text-sm text-red-400 rounded-lg bg-red-900/50" role="alert">
                        {error}
                    </div>
                {/if}

                {#if success}
                    <div class="p-4 mb-4 text-sm text-green-400 rounded-lg bg-green-900/50" role="alert">
                        Link reset password telah dikirim ke email atau nomor telepon Anda.
                    </div>
                {/if}

                <form
                    class="space-y-4 md:space-y-6"
                    on:submit|preventDefault={submitForm}
                >
                    <div>
                        <label for="email" class="block mb-2 text-sm font-medium text-slate-200">Email atau Nomor Telepon</label>
                        <input
                            bind:value={form.email}
                            type="text"
                            name="email"
                            id="email"
                            class="bg-slate-900/70 border border-slate-700 text-slate-50 sm:text-sm rounded-lg focus:ring-2 focus:ring-primary-400 focus:border-primary-400 focus:outline-none block w-full py-2.5 px-3 placeholder-slate-500"
                            placeholder="email@example.com atau 08xxxxxxxxxx"
                            required
                        />
                    </div>

                    <button type="submit" class="w-full text-sm font-medium rounded-full px-5 py-2.5 text-slate-950 bg-primary-400 hover:bg-primary-300 focus:ring-4 focus:outline-none focus:ring-primary-300">
                        Kirim Link Reset Password
                    </button>

                    <p class="text-sm font-light text-slate-400">
                        Ingat password Anda? <a href="/login" use:inertia class="font-medium text-primary-400 hover:underline">Login disini</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>

// packages/create-nara/templates/vue/resources/js/pages/auth/forgot-password.vue
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import { Link } from '@inertiajs/vue3';
import axios from 'axios';
import { api, Toast } from '../../components/helper';
import NaraIcon from '../../components/NaraIcon.vue';
import DarkModeToggle from '../../components/DarkModeToggle.vue';

const props = defineProps<{
  error?: string;
}>();

const form = ref({
  email: '',
  phone: '',
});

const success = ref(false);
const processing = ref(false);

onMounted(() => {
  if (props.error) {
    Toast(props.error, 'error');
  }
});

watch(() => props.error, (newError) => {
  if (newError) {
    Toast(newError, 'error');
  }
});

async function submit() {
  processing.value = true;
  const result = await api(() => axios.post("/forgot-password", form.value));
  processing.value = false;

  if (result.success) {
    success.value = true;
    form.value.email = "";
    form.value.phone = "";
  }
}
</script>

<template>
  <section class="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 text-slate-50">
    <!-- Header with dark mode toggle -->
    <header class="fixed inset-x-0 top-0 z-40 border-b border-slate-800/60 bg-slate-950/80 backdrop-blur-xl">
      <div class="max-w-6xl mx-auto flex h-16 items-center justify-between px-4 sm:h-20 sm:px-6 lg:px-8">
        <Link href="/" class="flex items-center gap-2">
          <img src="/nara.png" alt="Nara logo" class="h-7 w-7 rounded-lg object-cover" />
          <div class="flex flex-col leading-tight">
            <span class="text-sm font-semibold tracking-tight text-slate-50">Nara</span>
            <span class="text-[10px] uppercase tracking-[0.22em] text-slate-500">TypeScript framework</span>
          </div>
        </Link>
        <div class="flex items-center gap-3">
          <DarkModeToggle />
        </div>
      </div>
    </header>

    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto min-h-screen lg:py-0">
      <div class="flex items-center mb-6 text-2xl font-semibold text-slate-50">
        <NaraIcon />
      </div>
      <div class="w-full max-w-md rounded-3xl border border-slate-800/80 bg-slate-900/70 backdrop-blur-xl shadow-[0_24px_80px_rgba(15,23,42,0.8)] md:mt-0 sm:max-w-md xl:p-0">
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
          <h1 class="text-xl font-bold leading-tight tracking-tight text-slate-50 md:text-2xl">
            Reset Password
          </h1>

          <div v-if="success" class="p-4 mb-4 text-sm text-green-400 rounded-lg bg-green-900/50" role="alert">
            Link reset password telah dikirim ke email atau nomor telepon Anda.
          </div>

          <form class="space-y-4 md:space-y-6" @submit.prevent="submit">
            <div>
              <label for="email" class="block mb-2 text-sm font-medium text-slate-200">Email atau Nomor Telepon</label>
              <input
                v-model="form.email"
                type="text"
                name="email"
                id="email"
                class="bg-slate-900/70 border border-slate-700 text-slate-50 sm:text-sm rounded-lg focus:ring-2 focus:ring-primary-400 focus:border-primary-400 focus:outline-none block w-full py-2.5 px-3 placeholder-slate-500"
                placeholder="email@example.com atau 08xxxxxxxxxx"
                required
              />
            </div>

            <button type="submit" :disabled="processing"
                    class="w-full text-sm font-medium rounded-full px-5 py-2.5 text-slate-950 bg-primary-400 hover:bg-primary-300 focus:ring-4 focus:outline-none focus:ring-primary-300 disabled:opacity-50">
              {{ processing ? 'Mengirim...' : 'Kirim Link Reset Password' }}
            </button>

            <p class="text-sm font-light text-slate-400">
              Ingat password Anda? <Link href="/login" class="font-medium text-primary-400 hover:underline">Login disini</Link>
            </p>
          </form>
        </div>
      </div>
    </div>
  </section>
</template>
