// resources/Components/UserModal.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import Input from './Input.svelte';
  import Label from './Label.svelte';
  import Button from './Button.svelte';
  import Switch from './Switch.svelte';
  import * as dialog from "@zag-js/dialog";
  import { useMachine, normalizeProps, portal } from "@zag-js/svelte";
  import { Loader2 } from '@lucide/svelte';
  import type { UserForm, RoleInfo } from '../types';

  let {
    show = false,
    mode = 'create',
    form,
    isSubmitting = false,
    availableRoles = []
  }: {
    show?: boolean;
    mode?: 'create' | 'edit';
    form: UserForm;
    isSubmitting?: boolean;
    availableRoles?: RoleInfo[];
  } = $props();

  const dispatch = createEventDispatcher<{
    close: void;
    submit: UserForm;
  }>();

  const dialogService = useMachine(dialog.machine, {
    id: "user-modal",
    get open() { return show; },
    onOpenChange(details) {
      if (!details.open) dispatch('close');
    },
  });
  const dialogApi = $derived(dialog.connect(dialogService, normalizeProps));

  function handleClose(): void {
    dispatch('close');
  }

  function handleSubmit(): void {
    dispatch('submit', form);
  }

  function toggleRole(slug: string, checked: boolean): void {
    if (checked) {
      form.roles = [...(form.roles || []), slug];
    } else {
      form.roles = (form.roles || []).filter(r => r !== slug);
    }
  }

  function hasRole(slug: string): boolean {
    return form.roles?.includes(slug) ?? false;
  }
</script>

{#if dialogApi.open}
  <div use:portal>
    <div {...dialogApi.getBackdropProps()} class="fixed inset-0 z-50 bg-black/40 backdrop-blur-sm"></div>
    <div {...dialogApi.getPositionerProps()}>
      <div {...dialogApi.getContentProps()} class="bg-background fixed top-[50%] left-[50%] z-50 grid w-full max-w-[calc(100%-2rem)] translate-x-[-50%] translate-y-[-50%] rounded-2xl border border-border shadow-lg sm:max-w-md font-body overflow-hidden">

        <div class="px-6 pt-6 pb-5 border-b border-border">
          <span class="text-[10px] font-mono-accent uppercase tracking-widest text-primary mb-2 block">
            {mode === 'create' ? 'New User' : 'Edit User'}
          </span>
          <h2 {...dialogApi.getTitleProps()} class="font-heading font-semibold text-xl tracking-tight" style="font-feature-settings: 'ss01'">
            {mode === 'create' ? 'Create User' : 'Update User'}
          </h2>
          <p {...dialogApi.getDescriptionProps()} class="text-sm text-muted-foreground font-body mt-1">
            {mode === 'create' ? 'Add a new user to the system.' : 'Make changes to the user profile here.'}
          </p>
        </div>

        <form id="user-form" onsubmit={(e) => { e.preventDefault(); handleSubmit(); }}>
          <div class="px-6 py-5 space-y-5 max-h-[70vh] overflow-y-auto">
            <div class="space-y-2">
              <Label for="name" class="text-xs font-mono-accent uppercase tracking-widest text-muted-foreground">Full Name</Label>
              <Input id="name" type="text" bind:value={form.name} placeholder="Enter full name" class="rounded-xl h-11 bg-background border-border font-body text-sm" required />
            </div>
            <div class="space-y-2">
              <Label for="email" class="text-xs font-mono-accent uppercase tracking-widest text-muted-foreground">Email Address</Label>
              <Input id="email" type="email" bind:value={form.email} placeholder="user@example.com" class="rounded-xl h-11 bg-background border-border font-body text-sm" required />
            </div>
            <div class="space-y-2">
              <Label for="phone" class="text-xs font-mono-accent uppercase tracking-widest text-muted-foreground">Phone <span class="normal-case tracking-normal font-body text-muted-foreground">(optional)</span></Label>
              <Input id="phone" type="text" bind:value={form.phone} placeholder="+62 xxx xxxx xxxx" class="rounded-xl h-11 bg-background border-border font-body text-sm" />
            </div>
            <div class="space-y-2">
              <Label for="password" class="text-xs font-mono-accent uppercase tracking-widest text-muted-foreground">{mode === 'create' ? 'Password' : 'New Password'} <span class="normal-case tracking-normal font-body text-muted-foreground">(optional)</span></Label>
              <Input id="password" type="password" bind:value={form.password} placeholder={mode === 'create' ? 'Leave empty to use email' : 'Leave empty to keep current'} class="rounded-xl h-11 bg-background border-border font-body text-sm" />
            </div>

            <div class="space-y-3">
              <Label class="text-xs font-mono-accent uppercase tracking-widest text-muted-foreground">Roles</Label>
              <div class="grid grid-cols-2 gap-2">
                {#each availableRoles as role}
                  <div class="flex items-center gap-3 bg-card border border-border rounded-xl p-3 cursor-pointer hover:border-primary/40 transition-colors duration-200">
                    <Switch checked={hasRole(role.slug)} onCheckedChange={(c: boolean) => toggleRole(role.slug, c)} id="role-{role.slug}" />
                    <div>
                      <Label for="role-{role.slug}" class="text-sm font-heading font-semibold cursor-pointer capitalize">{role.name}</Label>
                      {#if role.description}
                        <p class="text-[10px] font-mono-accent text-muted-foreground mt-0.5 line-clamp-1">{role.description}</p>
                      {/if}
                    </div>
                  </div>
                {/each}
                {#if availableRoles.length === 0}
                  <p class="text-xs text-muted-foreground font-mono-accent col-span-2">No roles available</p>
                {/if}
              </div>
            </div>

            <div class="flex items-center gap-3 bg-card border border-border rounded-xl p-3 cursor-pointer hover:border-primary/40 transition-colors duration-200">
              <Switch bind:checked={form.is_verified} id="verified-status" />
              <div>
                <Label for="verified-status" class="text-sm font-heading font-semibold cursor-pointer">Verified</Label>
                <p class="text-xs font-mono-accent text-muted-foreground mt-0.5">Email confirmed</p>
              </div>
            </div>
          </div>
        </form>

        <div class="px-6 py-4 border-t border-border flex gap-2">
          <Button variant="outline" onclick={handleClose} disabled={isSubmitting} class="rounded-full font-mono-accent text-xs uppercase tracking-widest border-border hover:border-primary/40 hover:text-primary transition-colors duration-200">Cancel</Button>
          <Button type="submit" form="user-form" disabled={isSubmitting} class="rounded-full font-mono-accent text-xs uppercase tracking-widest hover:scale-105 active:scale-95 transition-transform duration-200">
            {#if isSubmitting}<Loader2 class="mr-2 h-4 w-4 animate-spin" />{/if}
            {mode === 'create' ? 'Create User' : 'Save Changes'}
          </Button>
        </div>

        <button {...dialogApi.getCloseTriggerProps()} class="absolute end-4 top-4 rounded-lg opacity-50 transition-opacity hover:opacity-100">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="size-4"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
          <span class="sr-only">Close</span>
        </button>
      </div>
    </div>
  </div>
{/if}

// packages/create-nara/templates/vue/resources/js/components/UserModal.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';

interface UserForm {
  name: string;
  email: string;
  phone?: string;
  is_admin: boolean;
  is_verified: boolean;
  password?: string;
}

const props = defineProps<{
  show: boolean;
  mode?: 'create' | 'edit';
  form: UserForm;
  isSubmitting?: boolean;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'submit', form: UserForm): void;
}>();

const handleClose = () => {
  emit('close');
};

const handleSubmit = () => {
  emit('submit', props.form);
};

const handleBackdropClick = (e: MouseEvent) => {
  if (e.target === e.currentTarget) {
    handleClose();
  }
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape' && props.show) {
    handleClose();
  }
};

onMounted(() => {
  window.addEventListener('keydown', handleKeyDown);
});

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeyDown);
});
</script>

<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition duration-300 ease-out"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition duration-200 ease-in"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <div
        v-if="show"
        class="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6"
        @click="handleBackdropClick"
        role="dialog"
        aria-modal="true"
        aria-labelledby="modal-title"
        tabindex="-1"
      >
        <!-- Background Blur & Overlay -->
        <div class="absolute inset-0 bg-black/70 backdrop-blur-md"></div>

        <!-- Decorative Elements -->
        <div class="absolute top-1/4 left-1/4 w-96 h-96 bg-accent-500/10 rounded-full blur-3xl pointer-events-none"></div>
        <div class="absolute bottom-1/4 right-1/4 w-64 h-64 bg-primary-500/10 rounded-full blur-3xl pointer-events-none"></div>

        <!-- Modal Container -->
        <Transition
          appear
          enter-active-class="transition duration-500 ease-out-back"
          enter-from-class="opacity-0 translate-y-12 scale-95"
          enter-to-class="opacity-100 translate-y-0 scale-100"
        >
          <div class="relative w-full max-w-lg">
            <!-- Glowing Border Effect -->
            <div class="absolute -inset-px bg-gradient-to-br from-accent-500/50 via-transparent to-primary-500/50 rounded-3xl blur-sm opacity-60"></div>

            <!-- Modal Content -->
            <div class="relative bg-white dark:bg-surface-dark rounded-3xl border border-slate-200 dark:border-white/10 overflow-hidden shadow-2xl">

              <!-- Header -->
              <div class="relative px-8 pt-8 pb-6 border-b border-slate-100 dark:border-white/5">
                <!-- Decorative Line -->
                <div class="absolute top-0 left-8 right-8 h-px bg-gradient-to-r from-transparent via-accent-500/50 to-transparent"></div>

                <div class="flex items-start justify-between">
                  <div>
                    <p class="text-[10px] font-bold uppercase tracking-[0.3em] text-accent-600 dark:text-accent-400 mb-2">
                      {{ mode === 'create' ? 'New Entry' : 'Edit Entry' }}
                    </p>
                    <h3 id="modal-title" class="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">
                      {{ mode === 'create' ? 'Create User' : 'Update User' }}
                    </h3>
                  </div>

                  <!-- Close Button -->
                  <button
                    class="group w-10 h-10 flex items-center justify-center rounded-full border border-slate-200 dark:border-white/10 hover:border-red-500/50 hover:bg-red-500/5 transition-all duration-300"
                    @click="handleClose"
                    :disabled="isSubmitting"
                    aria-label="Close modal"
                  >
                    <svg class="w-4 h-4 text-slate-400 group-hover:text-red-500 transition-colors" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                      <path d="M18 6L6 18M6 6l12 12" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                  </button>
                </div>
              </div>

              <!-- Form -->
              <form class="p-8 space-y-6" @submit.prevent="handleSubmit">

                <!-- Name Field -->
                <div class="group">
                  <label for="user-name" class="block text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400 mb-3">
                    Full Name
                  </label>
                  <div class="relative">
                    <input
                      id="user-name"
                      class="w-full px-0 py-3 bg-transparent border-0 border-b-2 border-slate-200 dark:border-white/10 text-lg text-slate-900 dark:text-white placeholder-slate-300 dark:placeholder-slate-600 focus:border-accent-500 dark:focus:border-accent-400 focus:ring-0 outline-none transition-colors"
                      type="text"
                      v-model="form.name"
                      placeholder="Enter full name"
                    />
                    <div class="absolute bottom-0 left-0 w-0 h-0.5 bg-accent-500 group-focus-within:w-full transition-all duration-500"></div>
                  </div>
                </div>

                <!-- Email Field -->
                <div class="group">
                  <label for="user-email" class="block text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400 mb-3">
                    Email Address
                  </label>
                  <div class="relative">
                    <input
                      id="user-email"
                      class="w-full px-0 py-3 bg-transparent border-0 border-b-2 border-slate-200 dark:border-white/10 text-lg text-slate-900 dark:text-white placeholder-slate-300 dark:placeholder-slate-600 focus:border-accent-500 dark:focus:border-accent-400 focus:ring-0 outline-none transition-colors"
                      type="email"
                      v-model="form.email"
                      placeholder="user@example.com"
                    />
                  </div>
                </div>

                <!-- Phone Field -->
                <div class="group">
                  <label for="user-phone" class="block text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400 mb-3">
                    Phone Number
                    <span class="text-slate-400 dark:text-slate-600 font-normal normal-case tracking-normal ml-1">(optional)</span>
                  </label>
                  <div class="relative">
                    <input
                      id="user-phone"
                      class="w-full px-0 py-3 bg-transparent border-0 border-b-2 border-slate-200 dark:border-white/10 text-lg text-slate-900 dark:text-white placeholder-slate-300 dark:placeholder-slate-600 focus:border-purple-500 dark:focus:border-purple-400 focus:ring-0 outline-none transition-colors font-mono"
                      type="text"
                      v-model="form.phone"
                      placeholder="+62 xxx xxxx xxxx"
                    />
                  </div>
                </div>

                <!-- Role & Status Toggles -->
                <div class="grid grid-cols-2 gap-4 pt-2">
                  <!-- Admin Toggle -->
                  <label class="group relative flex items-center gap-4 p-4 rounded-2xl border border-slate-200 dark:border-white/10 hover:border-accent-500/30 cursor-pointer transition-all duration-300" :class="{ 'bg-accent-500/5 border-accent-500/30': form.is_admin }">
                    <div class="relative">
                      <input
                        type="checkbox"
                        class="sr-only peer"
                        v-model="form.is_admin"
                      />
                      <div class="w-12 h-7 bg-slate-200 dark:bg-white/10 rounded-full peer-checked:bg-accent-500 transition-colors"></div>
                      <div class="absolute top-0.5 left-0.5 w-6 h-6 bg-white rounded-full shadow-md transform peer-checked:translate-x-5 transition-transform"></div>
                    </div>
                    <div>
                      <p class="text-sm font-bold text-slate-900 dark:text-white">Admin</p>
                      <p class="text-[10px] text-slate-400 dark:text-slate-500">Full access</p>
                    </div>
                  </label>

                  <!-- Verified Toggle -->
                  <label class="group relative flex items-center gap-4 p-4 rounded-2xl border border-slate-200 dark:border-white/10 hover:border-primary-500/30 cursor-pointer transition-all duration-300" :class="{ 'bg-primary-500/5 border-primary-500/30': form.is_verified }">
                    <div class="relative">
                      <input
                        type="checkbox"
                        class="sr-only peer"
                        v-model="form.is_verified"
                      />
                      <div class="w-12 h-7 bg-slate-200 dark:bg-white/10 rounded-full peer-checked:bg-primary-500 transition-colors"></div>
                      <div class="absolute top-0.5 left-0.5 w-6 h-6 bg-white rounded-full shadow-md transform peer-checked:translate-x-5 transition-transform"></div>
                    </div>
                    <div>
                      <p class="text-sm font-bold text-slate-900 dark:text-white">Verified</p>
                      <p class="text-[10px] text-slate-400 dark:text-slate-500">Email confirmed</p>
                    </div>
                  </label>
                </div>

                <!-- Password Field -->
                <div class="group pt-2">
                  <label for="user-password" class="block text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400 mb-3">
                    {{ mode === 'create' ? 'Password' : 'New Password' }}
                    <span class="text-slate-400 dark:text-slate-600 font-normal normal-case tracking-normal ml-1">(optional)</span>
                  </label>
                  <div class="relative">
                    <input
                      id="user-password"
                      class="w-full px-0 py-3 bg-transparent border-0 border-b-2 border-slate-200 dark:border-white/10 text-lg text-slate-900 dark:text-white placeholder-slate-300 dark:placeholder-slate-600 focus:border-accent-500 dark:focus:border-accent-400 focus:ring-0 outline-none transition-colors"
                      type="password"
                      v-model="form.password"
                      :placeholder="mode === 'create' ? 'Leave empty to use email' : 'Leave empty to keep current'"
                    />
                  </div>
                </div>

                <!-- Actions -->
                <div class="flex items-center justify-end gap-4 pt-6 border-t border-slate-100 dark:border-white/5">
                  <button
                    type="button"
                    class="px-6 py-3 text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors disabled:opacity-50"
                    @click="handleClose"
                    :disabled="isSubmitting"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    class="group relative px-8 py-3 bg-slate-900 dark:bg-white text-white dark:text-black text-xs font-bold uppercase tracking-wider rounded-full overflow-hidden hover:scale-105 active:scale-95 transition-transform disabled:opacity-50 disabled:hover:scale-100"
                    :disabled="isSubmitting"
                  >
                    <span class="relative z-10 flex items-center gap-2">
                      <template v-if="isSubmitting">
                        <svg class="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none">
                          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                        Saving...
                      </template>
                      <template v-else>
                        {{ mode === 'create' ? 'Create User' : 'Save Changes' }}
                        <svg class="w-4 h-4 transform group-hover:translate-x-1 transition-transform" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                          <path d="M5 12h14M12 5l7 7-7 7" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                      </template>
                    </span>
                    <div class="absolute inset-0 bg-gradient-to-r from-accent-500 to-primary-500 transform translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </Transition>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.ease-out-back {
  transition-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1);
}
</style>
