// resources/Components/Pagination.svelte
<script lang="ts">
  import { router } from '@inertiajs/svelte';
  import { cn } from '$lib/utils.js';
  import type { PaginationMeta } from '../types';
  import { ChevronLeft, ChevronRight } from '@lucide/svelte';

  let { meta, preserveState = true }: { meta: PaginationMeta; preserveState?: boolean } = $props();

  function goToPage(page: number): void {
    const url = new URL(window.location.href);
    url.searchParams.set('page', String(page));
    router.visit(url.pathname + url.search, { preserveScroll: true, preserveState });
  }

  function getPageNumbers(): number[] {
    const start = Math.max(1, Math.min(meta.page - 2, meta.totalPages - 4));
    return Array.from({ length: Math.min(5, meta.totalPages) }, (_, i) => start + i).filter(p => p <= meta.totalPages);
  }

  const showStartEllipsis = $derived(getPageNumbers()[0] > 1);
  const showEndEllipsis = $derived(getPageNumbers()[getPageNumbers().length - 1] < meta.totalPages);

  const linkBase = cn("inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 h-9 w-9");
  const navBtn = cn("inline-flex items-center justify-center gap-1 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 h-9 px-3 text-muted-foreground hover:bg-muted hover:text-foreground");
</script>

{#if meta.totalPages > 1}
  <div class="mt-6">
    <div class="flex items-center justify-between mb-2 text-xs text-muted-foreground">
      <span>Page {meta.page} of {meta.totalPages} ({meta.total} total)</span>
    </div>
    <nav class="mx-auto flex w-full justify-center">
      <ul class="flex flex-row items-center gap-1">
        <li>
          <button class={navBtn} onclick={() => goToPage(meta.page - 1)} disabled={!meta.hasPrev} aria-label="Go to previous page">
            <ChevronLeft class="size-4" /><span>Previous</span>
          </button>
        </li>

        {#if showStartEllipsis}
          <li><button class={linkBase} onclick={() => goToPage(1)}>1</button></li>
          <li><span class="flex h-9 w-9 items-center justify-center text-muted-foreground">…</span></li>
        {/if}

        {#each getPageNumbers() as pageNum}
          <li>
            <button
              class={cn(linkBase, pageNum === meta.page ? "bg-primary text-primary-foreground shadow" : "text-foreground hover:bg-muted")}
              onclick={() => goToPage(pageNum)}
              aria-current={pageNum === meta.page ? "page" : undefined}
            >{pageNum}</button>
          </li>
        {/each}

        {#if showEndEllipsis}
          <li><span class="flex h-9 w-9 items-center justify-center text-muted-foreground">…</span></li>
          <li><button class={linkBase} onclick={() => goToPage(meta.totalPages)}>{meta.totalPages}</button></li>
        {/if}

        <li>
          <button class={navBtn} onclick={() => goToPage(meta.page + 1)} disabled={!meta.hasNext} aria-label="Go to next page">
            <span>Next</span><ChevronRight class="size-4" />
          </button>
        </li>
      </ul>
    </nav>
  </div>
{/if}

// packages/inertia-vue/src/components/Pagination.vue
<script setup lang="ts">
import { computed } from 'vue';
import { router } from '@inertiajs/vue3';

interface PaginationMeta {
  page: number;
  total: number;
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
}

const props = withDefaults(defineProps<{
  meta: PaginationMeta;
  preserveState?: boolean;
}>(), {
  preserveState: true
});

const goToPage = (page: number) => {
  const url = new URL(window.location.href);
  url.searchParams.set('page', String(page));
  router.visit(url.pathname + url.search, {
    preserveScroll: true,
    preserveState: props.preserveState
  });
};

const pages = computed(() => {
  const length = Math.min(5, props.meta.totalPages);
  const start = Math.max(1, Math.min(props.meta.page - 2, props.meta.totalPages - 4));
  return Array.from({ length }, (_, i) => start + i).filter(p => p <= props.meta.totalPages);
});
</script>

<template>
  <div v-if="meta.totalPages > 1" class="flex items-center justify-between mt-6 text-xs text-slate-400">
    <div>
      Halaman {{ meta.page }} dari {{ meta.totalPages }} ({{ meta.total }} total)
    </div>
    <div class="flex items-center gap-2">
      <button
        class="px-3 py-1.5 rounded-full bg-slate-800 dark:bg-slate-200 hover:bg-slate-700 dark:hover:bg-slate-300 text-slate-100 dark:text-slate-800 transition disabled:opacity-50 disabled:cursor-not-allowed"
        @click="goToPage(meta.page - 1)"
        :disabled="!meta.hasPrev"
      >
        ← Prev
      </button>

      <button
        v-for="pageNum in pages"
        :key="pageNum"
        class="px-3 py-1.5 rounded-full transition"
        :class="pageNum === meta.page
          ? 'bg-primary-500 text-white'
          : 'bg-slate-800 dark:bg-slate-200 hover:bg-slate-700 dark:hover:bg-slate-300 text-slate-100 dark:text-slate-800'"
        @click="goToPage(pageNum)"
      >
        {{ pageNum }}
      </button>

      <button
        class="px-3 py-1.5 rounded-full bg-slate-800 dark:bg-slate-200 hover:bg-slate-700 dark:hover:bg-slate-300 text-slate-100 dark:text-slate-800 transition disabled:opacity-50 disabled:cursor-not-allowed"
        @click="goToPage(meta.page + 1)"
        :disabled="!meta.hasNext"
      >
        Next →
      </button>
    </div>
  </div>
</template>
