// packages/create-nara/templates/vue/resources/js/pages/auth/register.vue
<script setup lang="ts">
import { onMounted, watch } from 'vue';
import { useForm, Link } from '@inertiajs/vue3';
import { Toast, password_generator } from '../../utils/helper';
import NaraIcon from '../../components/NaraIcon.vue';

const props = defineProps<{
  error?: string;
}>();

const form = useForm({
  name: '',
  email: '',
  phone: '',
  password: '',
  password_confirmation: '',
});

onMounted(() => {
  if (props.error) {
    Toast(props.error, 'error');
  }
});

watch(() => props.error, (newError) => {
  if (newError) {
    Toast(newError, 'error');
  }
});

function generatePassword() {
  const retVal = password_generator(10);
  form.password = retVal;
  form.password_confirmation = retVal;
}

function submit() {
  if (form.password !== form.password_confirmation) {
    Toast("Password dan konfirmasi password harus sama", "error");
    return;
  }

  // Ensure phone is string as in Svelte logic
  const submitData = {
    ...form.data(),
    phone: form.phone.toString()
  };

  form.transform(() => submitData).post('/register');
}
</script>

<template>
  <div class="min-h-screen bg-white dark:bg-black text-slate-900 dark:text-slate-100 flex overflow-hidden">

    <!-- Right Panel: Visual (Swapped for Register) -->
    <div class="hidden lg:flex w-1/2 bg-surface-card-dark relative overflow-hidden items-center justify-center order-2 lg:order-1">
        <div class="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-30"></div>

        <!-- Abstract blobs -->
        <div class="absolute top-0 left-0 w-[600px] h-[600px] bg-info-500/20 rounded-full blur-[120px] -translate-y-1/2 -translate-x-1/2"></div>
        <div class="absolute bottom-0 right-0 w-[600px] h-[600px] bg-primary-500/10 rounded-full blur-[120px] translate-y-1/2 translate-x-1/2"></div>

        <div class="relative z-10 max-w-lg text-center p-12">
            <h2 class="text-6xl font-bold tracking-tighter text-white mb-6 leading-[0.9]">
              JOIN THE <br/>
              <span class="text-transparent bg-clip-text bg-gradient-to-r from-info-400 to-accent-300">REVOLUTION</span>
            </h2>
            <p class="text-xl text-slate-400 font-serif italic">
              "Build what others can't. Ship when others don't."
            </p>

            <!-- Terminal Decoration -->
            <div class="mt-12 text-left bg-black/50 backdrop-blur-md rounded-xl border border-white/10 p-6 font-mono text-xs text-slate-300 shadow-2xl transform -rotate-2 hover:rotate-0 transition-transform duration-500">
               <div class="flex gap-2 mb-4">
                 <div class="w-3 h-3 rounded-full bg-slate-700"></div>
                 <div class="w-3 h-3 rounded-full bg-slate-700"></div>
                 <div class="w-3 h-3 rounded-full bg-slate-700"></div>
               </div>
               <div class="space-y-2">
                  <div><span class="text-primary-400">$</span> init user --new</div>
                  <div class="text-slate-500">Creating workspace...</div>
                  <div class="text-slate-500">Allocating resources...</div>
                  <div><span class="text-info-400">✓</span> User created successfully.</div>
               </div>
            </div>
        </div>
    </div>

    <!-- Left Panel: Form -->
    <div class="w-full lg:w-1/2 flex flex-col justify-between p-8 lg:p-12 z-10 relative overflow-y-auto order-1 lg:order-2">
        <div>
            <Link href="/" class="text-2xl font-bold tracking-tighter flex items-center gap-2 justify-end lg:justify-start">
                <NaraIcon />
                <span>NARA.</span>
            </Link>
        </div>

        <div class="max-w-md w-full mx-auto mt-8 lg:mt-0">
            <h1 class="text-4xl lg:text-5xl font-bold tracking-tight mb-2">Create Account.</h1>
            <p class="text-slate-500 dark:text-slate-400 mb-8 text-lg">Start building your legacy.</p>

            <!-- Google Signup Button -->
            <div class="flex flex-col space-y-4 mb-8">
                <a href="/google/redirect"
                   class="group relative w-full flex items-center justify-center px-6 py-4 border border-slate-200 dark:border-white/10 rounded-xl bg-slate-50 dark:bg-white/5 hover:bg-slate-100 dark:hover:bg-white/10 transition-all duration-300">
                    <svg class="h-5 w-5 mr-3 transition-transform group-hover:scale-110" viewBox="0 0 24 24">
                        <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
                        <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
                        <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
                        <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
                    </svg>
                    <span class="font-medium text-slate-700 dark:text-slate-200">Sign up with Google</span>
                </a>

                <div class="relative py-2">
                    <div class="absolute inset-0 flex items-center">
                        <div class="w-full border-t border-slate-200 dark:border-white/10"></div>
                    </div>
                    <div class="relative flex justify-center text-xs uppercase tracking-widest">
                        <span class="bg-white dark:bg-black px-4 text-slate-400">Or via email</span>
                    </div>
                </div>
            </div>

            <form class="space-y-4" @submit.prevent="submit">
                <div class="space-y-1">
                    <label for="name" class="block text-sm font-medium text-slate-700 dark:text-slate-300 ml-1">Full Name</label>
                    <input v-model="form.name" required type="text" name="name" id="name"
                        class="w-full px-5 py-3 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl focus:ring-2 focus:ring-info-500/50 focus:border-info-500 outline-none transition-all dark:text-white placeholder:text-slate-400"
                        placeholder="Rama Ren" >
                    <span v-if="form.errors.name" class="text-xs text-red-500 ml-1">{{ form.errors.name }}</span>
                </div>

                <div class="space-y-1">
                    <label for="email" class="block text-sm font-medium text-slate-700 dark:text-slate-300 ml-1">Email</label>
                    <input v-model="form.email" required type="text" name="email" id="email"
                        class="w-full px-5 py-3 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl focus:ring-2 focus:ring-info-500/50 focus:border-info-500 outline-none transition-all dark:text-white placeholder:text-slate-400"
                        placeholder="nara@example.com" >
                    <span v-if="form.errors.email" class="text-xs text-red-500 ml-1">{{ form.errors.email }}</span>
                </div>

                <div class="grid grid-cols-2 gap-4">
                    <div class="space-y-1">
                        <label for="password" class="block text-sm font-medium text-slate-700 dark:text-slate-300 ml-1">Password</label>
                        <input v-model="form.password" required type="password" name="password" id="password"
                            placeholder="••••••••"
                            class="w-full px-5 py-3 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl focus:ring-2 focus:ring-info-500/50 focus:border-info-500 outline-none transition-all dark:text-white placeholder:text-slate-400" >
                    </div>
                    <div class="space-y-1">
                        <label for="confirm-password" class="block text-sm font-medium text-slate-700 dark:text-slate-300 ml-1">Confirm</label>
                        <input v-model="form.password_confirmation" type="password" name="confirm-password" id="confirm-password"
                            placeholder="••••••••"
                            class="w-full px-5 py-3 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl focus:ring-2 focus:ring-info-500/50 focus:border-info-500 outline-none transition-all dark:text-white placeholder:text-slate-400" >
                    </div>
                </div>
                <span v-if="form.errors.password" class="text-xs text-red-500 ml-1">{{ form.errors.password }}</span>

                <div class="flex justify-end">
                  <button type="button" @click="generatePassword" class="text-xs font-mono text-info-400 hover:text-info-300 transition-colors flex items-center gap-1">
                      <svg class="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12V7C21 6.46957 20.7893 5.96086 20.4142 5.58579C20.0391 5.21071 19.5304 5 19 5H5C4.46957 5 3.96086 5.21071 3.58579 5.58579C3.21071 5.96086 3 6.46957 3 7V17C3 17.5304 3.21071 18.0391 3.58579 18.4142C3.96086 18.7893 4.46957 19 5 19H12" stroke-linecap="round" stroke-linejoin="round"/></svg>
                      GENERATE SECURE PASSWORD
                  </button>
                </div>

                <button type="submit" :disabled="form.processing"
                    class="group w-full relative overflow-hidden rounded-xl bg-slate-900 dark:bg-white text-white dark:text-black font-bold text-lg py-4 transition-transform active:scale-[0.98] mt-4">
                    <span class="relative z-10">{{ form.processing ? 'CREATING...' : 'CREATE ACCOUNT' }}</span>
                    <div class="absolute inset-0 bg-info-500 transform translate-y-full transition-transform duration-300 group-hover:translate-y-0"></div>
                </button>

                <p class="text-center text-slate-500 dark:text-slate-400 mt-6">
                    Already have an account? <Link href="/login" class="font-bold text-info-500 dark:text-info-400 hover:underline">Login</Link>
                </p>
            </form>
        </div>

        <div class="text-xs text-slate-400 dark:text-slate-600 mt-8 lg:mt-0 text-right lg:text-left">
            © 2025 NARA INC.
        </div>
    </div>
  </div>
</template>

// resources/js/Pages/auth/register.svelte
<script lang="ts">
  import { inertia, router } from '@inertiajs/svelte'
  import { password_generator } from '$lib/utils/password';
  import { Toast } from '$lib/toast';
  import NaraIcon from '../../Components/NaraIcon.svelte';
  import DarkModeToggle from '../../Components/DarkModeToggle.svelte';
  import { fly } from 'svelte/transition';

  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { Label } from '$lib/components/ui/label';
  import { Alert, AlertDescription } from '$lib/components/ui/alert';
  import { Eye, EyeOff } from '@lucide/svelte';

  interface RegisterForm {
    email: string;
    password: string;
    name: string;
    phone: string;
    password_confirmation: string;
  }

  let form: RegisterForm = $state({
    email: '',
    password: '',
    name: '',
    phone: '',
    password_confirmation: '',
  });

  let showPassword = $state(false);
  let showConfirm = $state(false);

  let { error }: { error?: string } = $props();

  $effect(() => {
    if (error) Toast(error, 'error');
  });

  function submitForm(): void {
    if (form.password != form.password_confirmation) {
      Toast("Password dan konfirmasi password harus sama", "error");
      return;
    }

    form.phone = form.phone.toString()
    router.post("/register", form as Record<string, unknown>, {})
  }

  function generatePassword(): void {
    const retVal = password_generator(10);
    form.password = retVal
    form.password_confirmation = retVal
  }
</script>

<div class="min-h-screen bg-background text-foreground font-body transition-colors duration-500 relative overflow-hidden">

  <div class="absolute inset-0 opacity-[0.03] dark:opacity-[0.05] pointer-events-none bg-[radial-gradient(#000_1px,transparent_1px)] dark:bg-[radial-gradient(#fff_1px,transparent_1px)] [background-size:24px_24px]"></div>
  <div class="absolute top-1/4 left-1/4 w-[500px] h-[500px] bg-primary/10 rounded-full blur-[120px] pointer-events-none"></div>

  <nav class="fixed top-0 left-0 right-0 z-50 px-6 sm:px-12 flex justify-between items-center py-5">
    <a href="/" class="text-xl font-heading font-bold tracking-tighter hover:opacity-70 transition-opacity flex items-center gap-2" style="font-feature-settings: 'ss01'">
      <NaraIcon />
      <span>NARA.</span>
    </a>
    <DarkModeToggle />
  </nav>

  <div class="flex items-center justify-center min-h-screen px-6 py-24">
    <div class="w-full max-w-sm" in:fly={{ y: 20, duration: 800, delay: 100 }}>

      <div class="mb-8">
        <span class="block text-xs font-mono-accent font-semibold uppercase tracking-widest text-primary mb-3">New account</span>
        <h1 class="text-4xl font-heading font-bold tracking-tighter" style="font-feature-settings: 'ss01'">Create Account.</h1>
      </div>

      {#if error}
        <Alert variant="destructive" class="mb-6">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      {/if}

      <div class="flex flex-col gap-4 mb-8">
        <a href="/google/redirect"
           class="group w-full flex items-center justify-center px-6 py-3.5 border border-border bg-card hover:border-primary/40 hover:bg-secondary rounded-2xl transition-all duration-300 cursor-pointer">
          <svg class="h-4 w-4 mr-3 shrink-0" viewBox="0 0 24 24">
            <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
            <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
            <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
            <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
          </svg>
          <span class="font-body font-medium text-foreground text-sm">Sign up with Google</span>
        </a>

        <div class="relative py-1">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-border"></div>
          </div>
          <div class="relative flex justify-center">
            <span class="bg-background px-4 text-muted-foreground font-mono-accent text-[10px] uppercase tracking-widest">Or via email</span>
          </div>
        </div>
      </div>

      <form class="space-y-4" onsubmit={(e) => { e.preventDefault(); submitForm(); }}>
        <div class="space-y-2">
          <Label for="name">Full Name</Label>
          <Input bind:value={form.name} required type="text" name="name" id="name" placeholder="Rama Ren" />
        </div>

        <div class="space-y-2">
          <Label for="email">Email</Label>
          <Input bind:value={form.email} required type="text" name="email" id="email" placeholder="nara@example.com" />
        </div>

        <div class="grid grid-cols-2 gap-3">
          <div class="space-y-2">
            <Label for="password">Password</Label>
            <div class="relative">
              <Input bind:value={form.password} required type={showPassword ? 'text' : 'password'} name="password" id="password" placeholder="••••••••" class="pr-10" />
              <button type="button" onclick={() => showPassword = !showPassword} class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors duration-200 cursor-pointer">
                {#if showPassword}
                  <EyeOff class="w-4 h-4" />
                {:else}
                  <Eye class="w-4 h-4" />
                {/if}
              </button>
            </div>
          </div>
          <div class="space-y-2">
            <Label for="confirm-password">Confirm</Label>
            <div class="relative">
              <Input bind:value={form.password_confirmation} required type={showConfirm ? 'text' : 'password'} name="confirm-password" id="confirm-password" placeholder="••••••••" class="pr-10" />
              <button type="button" onclick={() => showConfirm = !showConfirm} class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors duration-200 cursor-pointer">
                {#if showConfirm}
                  <EyeOff class="w-4 h-4" />
                {:else}
                  <Eye class="w-4 h-4" />
                {/if}
              </button>
            </div>
          </div>
        </div>

        <div class="flex justify-end">
          <Button variant="ghost" size="sm" type="button" onclick={generatePassword} class="text-xs font-mono-accent text-primary hover:text-primary/80 transition-colors flex items-center gap-1.5 cursor-pointer h-auto py-1 px-0">
            <svg class="w-3 h-3 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12V7C21 6.46957 20.7893 5.96086 20.4142 5.58579C20.0391 5.21071 19.5304 5 19 5H5C4.46957 5 3.96086 5.21071 3.58579 5.58579C3.21071 5.96086 3 6.46957 3 7V17C3 17.5304 3.21071 18.0391 3.58579 18.4142C3.96086 18.7893 4.46957 19 5 19H12" stroke-linecap="round" stroke-linejoin="round"/></svg>
            GENERATE SECURE PASSWORD
          </Button>
        </div>

        <Button type="submit" size="lg" class="w-full rounded-full py-6 font-heading font-semibold tracking-wide hover:scale-105 active:scale-95 transition-transform text-base shadow-sm mt-2">
          Create Account
        </Button>

        <p class="text-center text-muted-foreground font-body text-sm">
          Already have an account?
          <a href="/login" use:inertia class="font-semibold text-primary hover:underline">Sign in</a>
        </p>
      </form>
    </div>
  </div>

  <footer class="absolute bottom-0 left-0 right-0 px-6 py-5 flex justify-center">
    <span class="text-xs font-mono-accent text-muted-foreground uppercase tracking-widest">&copy; {new Date().getFullYear()} NARA FRAMEWORK</span>
  </footer>

</div>
